defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: default

title: JeongTaeYeong
subtitle: OpenSoftware-WebSite

# Side Menu Links
menu:
  - text: Portfolio
    link: /Menu/
    icon: ""

  - text: Skills & Offers
    link: /Menu/skills-and-offers
    icon: ""

  - text: Contact Me
    link: /Menu/contact
    icon: ""

  - text: My Resume
    link: /Menu/resume
    icon: ""

  - text: Post
    link: /Menu/Post/ssd
    icon: ""
    
# Socialmedia Icons
social_icons:
  - name: github
    link: https://github.com/Paransaik/
    icon: fab fa-github-square

  - name: facebook
    link: https://facebook.com/taeyeong419
    icon: fab fa-facebook-square



    
